version: 0.1

phases:
  build:
    commands:
      - echo ====== BUILD STARTED =========
  post_build:
    commands:
      - sbt executable
      - mv target/executable/gitbucket.war gitbucket.war
artifacts:
  files:
    - gitbucket.war
