version: 0.2
env:
  variables:
    TEST_ENV_VARIABLE: gitbucket.war
phases:
  install:
    runtime-versions:
      java: openjdk8
build:
    commands:
      - sbt executable   # generate build
    artifacts:
      files:
        - target/executable/gitbucket.war
