version: 0.1

phases:
  build:
    commands:
      - echo buildspec cur1osityay/gitbucket on use
  post_build:
    commands:
      - sbt executable
      - mv target/executable/gitbucket.war gitbucket.war
artifacts:
  files:
    - gitbucket.war
